Update result parsing script

diff --git a/.github/workflows/end-to-end.yml b/.github/workflows/end-to-end.yml
--- a/.github/workflows/end-to-end.yml
+++ b/.github/workflows/end-to-end.yml
@@ -107,14 +107,26 @@ jobs:
         # Parse the JSON string
         RESULTS='${{ steps.upload.outputs.MAESTRO_CLOUD_FLOW_RESULTS }}'
           
+        # Check if RESULTS is empty or null
+        if [ -z "$RESULTS" ]; then
+          echo "Error: No results found"
+          exit 1
+        fi
+    
         # Check if any flow was not successful
-        NON_SUCCESS_FLOWS=$(echo $RESULTS | jq '[.[] | select(.status != "SUCCESS")]')
-        NON_SUCCESS_COUNT=$(echo $NON_SUCCESS_FLOWS | jq 'length')
-          
+        NON_SUCCESS_FLOWS=$(echo "$RESULTS" | jq -r '[.[] | select(.status != "SUCCESS")]')
+        NON_SUCCESS_COUNT=$(echo "$NON_SUCCESS_FLOWS" | jq -r 'length')
+    
+        # Check if NON_SUCCESS_COUNT is a number
+        if ! [[ "$NON_SUCCESS_COUNT" =~ ^[0-9]+$ ]]; then
+          echo "Error: Invalid non-success count"
+          exit 1
+        fi
+    
         if [ "$NON_SUCCESS_COUNT" -gt 0 ]; then
           echo "Error: Some flows were not successful"
           echo "Details of non-successful flows:"
-          echo $NON_SUCCESS_FLOWS | jq '.'
+          echo "$NON_SUCCESS_FLOWS" | jq '.'
           exit 1
         else
           echo "All flows were successful"
