Switch to use mobile dev action and manually parse the results

diff --git a/.github/workflows/end-to-end.yml b/.github/workflows/end-to-end.yml
--- a/.github/workflows/end-to-end.yml
+++ b/.github/workflows/end-to-end.yml
@@ -69,7 +69,7 @@ jobs:
     name: End to end Tests
     needs: build-end-to-end-tests
     runs-on: macos-15
-    timeout-minutes: 120
+    timeout-minutes: 150
     strategy:
       matrix:
         test-tag: [release, privacy, securityTest, adClick]
@@ -87,13 +87,39 @@ jobs:
         name: duckduckgo-ios-app
         path: DerivedData/Build/Products/Debug-iphonesimulator/DuckDuckGo.app
 
-    - name: Install Maestro
-      run: |
-        export MAESTRO_VERSION=1.39.1; curl -Ls "https://get.maestro.mobile.dev" | bash
-
     - name: End to End tests
+      id: upload
+      uses: mobile-dev-inc/action-maestro-cloud@v1.9.7
+      with:
+        api-key: ${{ secrets.ROBIN_API_KEY }}
+        project-id: ${{ secrets.ROBIN_PROJECT_KEY }}
+        name: ${{ matrix.test-tag }}_${{ github.sha }}
+        timeout: 120
+        app-file: DerivedData/Build/Products/Debug-iphonesimulator/DuckDuckGo.app
+        workspace: .maestro
+        include-tags: ${{ matrix.test-tag }}
+        env: ONBOARDING_COMPLETED=true
+        ios-version: 17
+
+    - name: Process Robin Results
+      if: always()
       run: |
-        export PATH="$PATH":"$HOME/.maestro/bin"; maestro cloud --apiKey ${{ secrets.ROBIN_API_KEY }} --project-id ${{ secrets.ROBIN_PROJECT_KEY }} -e ONBOARDING_COMPLETED=true --fail-on-timeout=true --fail-on-cancellation=true --timeout=150 --ios-version=17 --include-tags=${{ matrix.test-tag }} DerivedData/Build/Products/Debug-iphonesimulator/DuckDuckGo.app .maestro/
+        # Parse the JSON string
+        RESULTS='${{ steps.upload.outputs.MAESTRO_CLOUD_FLOW_RESULTS }}'
+          
+        # Check if any flow was not successful
+        NON_SUCCESS_FLOWS=$(echo $RESULTS | jq '[.[] | select(.status != "SUCCESS")]')
+        NON_SUCCESS_COUNT=$(echo $NON_SUCCESS_FLOWS | jq 'length')
+          
+        if [ "$NON_SUCCESS_COUNT" -gt 0 ]; then
+          echo "Error: Some flows were not successful"
+          echo "Details of non-successful flows:"
+          echo $NON_SUCCESS_FLOWS | jq '.'
+          exit 1
+        else
+          echo "All flows were successful"
+        fi
+      shell: bash
   
   # notify-failure:
   #   name: Notify on failure
