New iOS automated workflows

diff --git a/.github/workflows/ios-release.yml b/.github/workflows/ios-release.yml
--- a/.github/workflows/ios-release.yml
+++ b/.github/workflows/ios-release.yml
@@ -15,20 +15,51 @@ on:
         description: "Asana release task URL"
         required: false
         type: string
-
-  pull_request:
-    branches:
-    - release/**
-    - hotfix/**
-    - '!release/**-' # filter out PRs matching that pattern
-    - '!hotfix/**-'
-    types: [closed]
+  workflow_call:
+    inputs:
+      asana-task-url:
+        description: "Asana release task URL"
+        required: true
+        type: string
+      branch:
+        description: "Branch name"
+        required: false
+        type: string
+      destination: 
+        description: "Upload destination (TestFlight or App Store)"
+        required: false
+        default: testflight
+        type: string
+    secrets:
+      APPLE_API_KEY_BASE64:
+        required: true
+      APPLE_API_KEY_ID:
+        required: true
+      APPLE_API_KEY_ISSUER:
+        required: true
+      ASANA_ACCESS_TOKEN:
+        required: true
+      AWS_ACCESS_KEY_ID:
+        required: true
+      AWS_SECRET_ACCESS_KEY:
+        required: true
+      MATCH_PASSWORD:
+        required: true
+      MM_WEBHOOK_URL:
+        required: true
+      SSH_PRIVATE_KEY_FASTLANE_MATCH:
+        required: true
 
 jobs:
   make-release:
     if: github.event.action == 0 || (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'Merge triggers release')) # empty string returns 0; for case when workflow is triggered manually
     runs-on: macos-15-xlarge
     name: Make App Store Connect Release
+
+    env:
+      destination: ${{ github.event.inputs.destination || inputs.destination }}
+      asana-task-url: ${{ github.event.inputs.asana-task-url || inputs.asana-task-url }}
+      branch: ${{ inputs.branch || github.ref_name }}
 
     steps:
 
@@ -40,7 +71,7 @@ jobs:
 
     - name: Assert release branch
       run: |
-        case "${{ github.ref }}" in
+        case "${branch}" in
           *release/*) ;;
           *hotfix/*) ;;
           *coldfix/*) ;;
@@ -53,9 +84,10 @@ jobs:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}
 
     - name: Check out the code
-      uses: actions/checkout@v3
+      uses: actions/checkout@v4
       with:
         submodules: recursive
+        ref: ${{ env.branch }}
 
     - name: Select Xcode
       run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer
@@ -82,16 +114,9 @@ jobs:
         name: DuckDuckGo-${{ steps.destination.outputs.destination }}-dSYM-${{ env.app_version }}
         path: ${{ env.dsyms_path }}
 
-    - name: Get Asana Task ID
-      id: get-task-id
-      if: ${{ always() && github.event.inputs.asana-task-url }}
-      run: |
-        task_url_regex='^https://app.asana.com/[0-9]/[0-9]*/([0-9]*)/f$'
-        if [[ "${{ github.event.inputs.asana-task-url }}" =~ ${task_url_regex} ]]; then
-          echo "task_id=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
-        else
-          echo "::error::Asana Task URL has incorrect format (attempted to match ${task_url_regex})."
-        fi
+    - name: Extract Asana Task ID
+      id: task-id
+      run: bundle exec fastlane run asana_extract_task_id task_url:"${{ env.asana-task-url }}"
 
     - name: Upload debug symbols to Asana
       if: ${{ always() && github.event.inputs.asana-task-url }}
@@ -102,7 +127,7 @@ jobs:
           asana_dsyms_path="${{ github.workspace }}/DuckDuckGo-${{ env.app_version }}-dSYM.zip"
           mv -f "${{ env.dsyms_path }}" "$asana_dsyms_path"
 
-          curl -s "https://app.asana.com/api/1.0/tasks/${{ steps.get-task-id.outputs.task_id }}/attachments" \
+          curl -s "https://app.asana.com/api/1.0/tasks/${{ steps.task-id.outputs.task_id }}/attachments" \
             -H "Authorization: Bearer ${{ secrets.ASANA_ACCESS_TOKEN }}" \
             --form "file=@${asana_dsyms_path};type=application/zip"
         fi
@@ -118,19 +143,40 @@ jobs:
         if [[ -f ${{ env.dsyms_path }} ]]; then
           aws s3 cp "${{ env.dsyms_path }}" ${{ env.DSYM_S3_PATH }}
         fi
+    
+    - name: Get tasks since last internal release and set vars
+      id: asana-templates
+      env:
+        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        tasks="$(./scripts/update_asana_for_release.sh list-tasks-in-last-internal-release)"
+        echo "WORKFLOW_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
+        echo "TASKS_SINCE_LAST_INTERNAL_RELEASE=$tasks" >> $GITHUB_ENV
+        if [[ -n "${TASKS_SINCE_LAST_INTERNAL_RELEASE}" ]]; then
+          echo "release-task-comment-template=internal-release-complete-with-tasks" >> $GITHUB_OUTPUT
+        else
+          echo "release-task-comment-template=internal-release-complete" >> $GITHUB_OUTPUT
+        fi
+
+    - name: Add a comment to the release task
+      if: success()
+      env:
+        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+        WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      run: |
+        bundle exec fastlane run asana_add_comment \
+          task_url:"${{ env.asana-task-url }}" \
+          template_name:"${{ steps.asana-templates.outputs.release-task-comment-template }}"
 
     - name: Send Mattermost message
-      if: ${{ success() || failure() }} # Don't execute when cancelled
+      if: success() || failure()
       env:
         WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        DESTINATION: ${{ steps.destination.outputs.destination }}
+        DESTINATION: ${{ env.destination }}
+        PLATFORM: iOS
       run: |
-        export MM_USER_HANDLE=$(base64 -d <<< ${{ secrets.MM_HANDLES_BASE64 }} | jq ".${{ github.actor }}" | tr -d '"')
-
-        if [[ -z "${MM_USER_HANDLE}" ]]; then
-            echo "Mattermost user handle not known for ${{ github.actor }}, skipping sending message"
-        else
-            curl -s -H 'Content-type: application/json' \
-                -d "$(envsubst < ./scripts/assets/appstore-release-mm-template.json | jq ".${{ job.status }}")" \
-                ${{ secrets.MM_WEBHOOK_URL }}
-        fi
+        bundle exec fastlane run mattermost_send_message \
+          mattermost_webhook_url:${{ secrets.MM_WEBHOOK_URL }} \
+          github_handle:${{ github.actor }} \
+          template_name:$([[ "${{ job.status }}" == "success" ]] && echo "public-release-complete" || echo "public-release-failed")
